// <auto-generated />
using System;
using Gestão_Epi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestão_Epi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Gestão_Epi.Entities.Colaborador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("matricula")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("setor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("colaborador");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Epi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ca")
                        .HasColumnType("int");

                    b.Property<string>("cor")
                        .HasColumnType("longtext");

                    b.Property<string>("descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("fabricante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tamanho")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly?>("validade")
                        .HasColumnType("date");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("epi");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Estoque", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("epi_id")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "epi_id" }, "epi_id")
                        .IsUnique();

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Notificacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("colaborador_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_devolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_limite")
                        .HasColumnType("datetime");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("retirada_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("'PENDENTE'");

                    b.Property<int?>("visitante_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "colaborador_id" }, "colaborador_id");

                    b.HasIndex(new[] { "retirada_id" }, "retirada_id")
                        .IsUnique();

                    b.HasIndex(new[] { "visitante_id" }, "visitante_id");

                    b.ToTable("notificacao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("perfil");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Perfil_Permissao", b =>
                {
                    b.Property<int>("perfil_id")
                        .HasColumnType("int");

                    b.Property<int>("permissao_id")
                        .HasColumnType("int");

                    b.HasKey("perfil_id", "permissao_id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "permissao_id" }, "permissao_id");

                    b.ToTable("perfil_permissao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Permissao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("descricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "codigo" }, "codigo")
                        .IsUnique();

                    b.ToTable("permissao");

                    b.HasData(
                        new
                        {
                            id = 1,
                            codigo = "EPI_CADASTRAR",
                            descricao = "PERMITE REALIZAR CADASTRO DE EPI"
                        },
                        new
                        {
                            id = 2,
                            codigo = "EPI_EDITAR",
                            descricao = "PERMITE REALIZAR EDIÇÃO DE EPI"
                        },
                        new
                        {
                            id = 3,
                            codigo = "EPI_DELETAR",
                            descricao = "PERMITE DELETAR EPI"
                        },
                        new
                        {
                            id = 4,
                            codigo = "EPI_LISTAR",
                            descricao = "PERMITE LISTAR EPIS"
                        },
                        new
                        {
                            id = 5,
                            codigo = "USUARIO_CADASTRAR",
                            descricao = "PERMITE REALIZAR CADASTRO DE USUÁRIO"
                        },
                        new
                        {
                            id = 6,
                            codigo = "USUARIO_EDITAR",
                            descricao = "PERMITE REALIZAR EDIÇÃO DE USUÁRIO"
                        },
                        new
                        {
                            id = 7,
                            codigo = "USUARIO_DELETAR",
                            descricao = "PERMITE DELETAR USUÁRIO"
                        },
                        new
                        {
                            id = 8,
                            codigo = "USUARIO_LISTAR",
                            descricao = "PERMITE LISTAR USUÁRIO"
                        },
                        new
                        {
                            id = 9,
                            codigo = "PERFIL_CADASTRAR",
                            descricao = "PERMITE REALIZAR CADASTRO DE PERFIL"
                        },
                        new
                        {
                            id = 10,
                            codigo = "PERFIL_EDITAR",
                            descricao = "PERMITE REALIZAR EDIÇÃO DE PERFIL"
                        },
                        new
                        {
                            id = 11,
                            codigo = "PERFIL_DELETAR",
                            descricao = "PERMITE DELETAR PERFIL"
                        },
                        new
                        {
                            id = 12,
                            codigo = "PERFIL_LISTAR",
                            descricao = "PERMITE LISTAR PERFIS"
                        },
                        new
                        {
                            id = 13,
                            codigo = "RETIRADA_REGISTRAR",
                            descricao = "PERMITE REGISTRAR SAÍDA EPI"
                        },
                        new
                        {
                            id = 14,
                            codigo = "DEVOLUCAO_REGISTRAR",
                            descricao = "PERMITE REGISTRAR ENTRADA EPI"
                        },
                        new
                        {
                            id = 15,
                            codigo = "ESTOQUE_LISTAR",
                            descricao = "PERMITE LISTAR ESTOQUE"
                        },
                        new
                        {
                            id = 16,
                            codigo = "ESTOQUE_ENTRADA",
                            descricao = "PERMITE AJUSTAR ESTOQUE(ENTRADA)"
                        },
                        new
                        {
                            id = 17,
                            codigo = "ESTOQUE_SAIDA",
                            descricao = "PERMITE AJUSTAR ESTOQUE(SAÍDA)"
                        },
                        new
                        {
                            id = 18,
                            codigo = "VISITANTE_CADASTRAR",
                            descricao = "PERMITE REALIZAR CADASTRO DE VISITANTE"
                        },
                        new
                        {
                            id = 19,
                            codigo = "VISITANTE_EDITAR",
                            descricao = "PERMITE REALIZAR EDIÇÃO VISITANTE"
                        },
                        new
                        {
                            id = 20,
                            codigo = "VISITANTE_DELETAR",
                            descricao = "PERMITE DELETAR VISITANTE"
                        },
                        new
                        {
                            id = 21,
                            codigo = "VISITANTE_LISTAR",
                            descricao = "PERMITE LISTAR VISITANTES"
                        },
                        new
                        {
                            id = 22,
                            codigo = "COLABORADOR_CADASTRAR",
                            descricao = "PERMITE REALIZAR CADASTRO DE COLABORADOR"
                        },
                        new
                        {
                            id = 23,
                            codigo = "COLABORADOR_EDITAR",
                            descricao = "PERMITE REALIZAR EDIÇÃO DE COLABORADOR"
                        },
                        new
                        {
                            id = 24,
                            codigo = "COLABORADOR_DELETAR",
                            descricao = "PERMITE DELETAR COLABORADOR"
                        },
                        new
                        {
                            id = 25,
                            codigo = "COLABORADOR_LISTAR",
                            descricao = "PERMITE LISTAR COLABORADORES"
                        });
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Retirada_devolucao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("colaborador_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_devolucao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_retirada")
                        .HasColumnType("datetime");

                    b.Property<int>("epi_id")
                        .HasColumnType("int");

                    b.Property<string>("justificativa_devolucao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("justificativa_retirada")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int?>("visitante_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "colaborador_id" }, "colaborador_id")
                        .HasDatabaseName("colaborador_id1");

                    b.HasIndex(new[] { "epi_id" }, "epi_id")
                        .HasDatabaseName("epi_id1");

                    b.HasIndex(new[] { "usuario_id" }, "usuario_id");

                    b.HasIndex(new[] { "visitante_id" }, "visitante_id")
                        .HasDatabaseName("visitante_id1");

                    b.ToTable("retirada_devolucao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("perfil_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("senhaHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(64)");

                    b.Property<byte[]>("senhaSalt")
                        .IsRequired()
                        .HasColumnType("VARBINARY(128)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "perfil_id" }, "fk_perfil");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Visitante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("documento");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("visitante");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Estoque", b =>
                {
                    b.HasOne("Gestão_Epi.Entities.Epi", "epi")
                        .WithOne("estoque")
                        .HasForeignKey("Gestão_Epi.Entities.Estoque", "epi_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("estoque_ibfk_1");

                    b.Navigation("epi");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Notificacao", b =>
                {
                    b.HasOne("Gestão_Epi.Entities.Colaborador", "colaborador")
                        .WithMany("notificacao")
                        .HasForeignKey("colaborador_id")
                        .HasConstraintName("notificacao_ibfk_1");

                    b.HasOne("Gestão_Epi.Entities.Retirada_devolucao", "retirada")
                        .WithOne("notificacao")
                        .HasForeignKey("Gestão_Epi.Entities.Notificacao", "retirada_id")
                        .IsRequired()
                        .HasConstraintName("notificacao_ibfk_3");

                    b.HasOne("Gestão_Epi.Entities.Visitante", "visitante")
                        .WithMany("notificacao")
                        .HasForeignKey("visitante_id")
                        .HasConstraintName("notificacao_ibfk_2");

                    b.Navigation("colaborador");

                    b.Navigation("retirada");

                    b.Navigation("visitante");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Perfil_Permissao", b =>
                {
                    b.HasOne("Gestão_Epi.Entities.Perfil", "perfil")
                        .WithMany("perfil_Permissao")
                        .HasForeignKey("perfil_id")
                        .IsRequired()
                        .HasConstraintName("perfil_permissao_ibfk_1");

                    b.HasOne("Gestão_Epi.Entities.Permissao", "permissao")
                        .WithMany("perfil_Permissao")
                        .HasForeignKey("permissao_id")
                        .IsRequired()
                        .HasConstraintName("perfil_permissao_ibfk_2");

                    b.Navigation("perfil");

                    b.Navigation("permissao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Retirada_devolucao", b =>
                {
                    b.HasOne("Gestão_Epi.Entities.Colaborador", "colaborador")
                        .WithMany("retirada_devolucao")
                        .HasForeignKey("colaborador_id")
                        .HasConstraintName("retirada_devolucao_ibfk_3");

                    b.HasOne("Gestão_Epi.Entities.Epi", "epi")
                        .WithMany("retirada_devolucao")
                        .HasForeignKey("epi_id")
                        .IsRequired()
                        .HasConstraintName("retirada_devolucao_ibfk_2");

                    b.HasOne("Gestão_Epi.Entities.Usuario", "usuario")
                        .WithMany("retirada_devolucao")
                        .HasForeignKey("usuario_id")
                        .IsRequired()
                        .HasConstraintName("retirada_devolucao_ibfk_1");

                    b.HasOne("Gestão_Epi.Entities.Visitante", "visitante")
                        .WithMany("retirada_devolucao")
                        .HasForeignKey("visitante_id")
                        .HasConstraintName("retirada_devolucao_ibfk_4");

                    b.Navigation("colaborador");

                    b.Navigation("epi");

                    b.Navigation("usuario");

                    b.Navigation("visitante");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Usuario", b =>
                {
                    b.HasOne("Gestão_Epi.Entities.Perfil", "perfil")
                        .WithMany("usuario")
                        .HasForeignKey("perfil_id")
                        .IsRequired()
                        .HasConstraintName("fk_perfil");

                    b.Navigation("perfil");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Colaborador", b =>
                {
                    b.Navigation("notificacao");

                    b.Navigation("retirada_devolucao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Epi", b =>
                {
                    b.Navigation("estoque");

                    b.Navigation("retirada_devolucao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Perfil", b =>
                {
                    b.Navigation("perfil_Permissao");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Permissao", b =>
                {
                    b.Navigation("perfil_Permissao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Retirada_devolucao", b =>
                {
                    b.Navigation("notificacao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Usuario", b =>
                {
                    b.Navigation("retirada_devolucao");
                });

            modelBuilder.Entity("Gestão_Epi.Entities.Visitante", b =>
                {
                    b.Navigation("notificacao");

                    b.Navigation("retirada_devolucao");
                });
#pragma warning restore 612, 618
        }
    }
}
